//LOADING
export const SET_LOADING = "SET_LOADING";

//WORD
export const SET_TARGET_WORD = "SET_TARGET_WORD";
export const SET_GUESSED_LETTER = "SET_GUESSED_LETTER";
export const CLEAR_GUESSED_WORD = "CLEAR_GUESSED_WORD";
export const CLEAR_PREVIOUS_GUESSED_WORDS = "CLEAR_PREVIOUS_GUESSED_WORDS";
export const SET_CORRECT_ANSWER = "SET_CORRECT_ANSWER";
// export const SET_LENGTH = "SET_LENGTH";
export const ADD_GUESSED_WORD = "ADD_GUESSED_WORD";
export const SET_NEXT_LETTER = "SET_NEXT_LETTER";
export const REMOVE_LAST_LETTER = "REMOVE_LAST_LETTER";
export const SUBMIT_WORD = "SUBMIT_WORD";

//GAME
// export const SET_SCORE = "SET_SCORE";
// export const SET_MODE = "SET_MODE";
// export const SET_TIMER = "SET_TIMER";
// export const SET_GAME_TIME = "SET_GAME_TIME";
// export const SET_SECONDS_ELAPSED = "SET_SECONDS_ELAPSED";
// export const CHANGE_PALETTE = "CHANGE_PALETTE";
// export const SET_NEW_PALETTE = "SET_NEW_PALETTE";
// export const SET_TRANSITIONING = "SET_TRANSITIONING";
//
// //Settings
// export const SET_MAX_WORD_LENGTH = "SET_MAX_WORD_LENGTH";
// export const SET_MAX_ASCENDING_WORD_LENGTH = "SET_MAX_ASCENDING_WORD_LENGTH";
// export const SET_MIN_WORD_LENGTH = "SET_MIN_WORD_LENGTH";
// export const SET_SETTINGS_VISIBILITY = "SET_SETTINGS_VISIBILITY";
